In [1]:
#done
! wget https://www.dropbox.com/s/78rnri07w9fipbx/google_stock_price_train.csv?dl=0

--2020-12-08 14:47:04--  https://www.dropbox.com/s/78rnri07w9fipbx/google_stock_price_train.csv?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.3.1, 2620:100:6018:1::a27d:301
Connecting to www.dropbox.com (www.dropbox.com)|162.125.3.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/78rnri07w9fipbx/google_stock_price_train.csv [following]
--2020-12-08 14:47:04--  https://www.dropbox.com/s/raw/78rnri07w9fipbx/google_stock_price_train.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc37cc22b4846ed01cb853dd2a34.dl.dropboxusercontent.com/cd/0/inline/BEqPOTOtNPaXYM0P7tSMoCaKJLNsSZvc6LzrbmecjeTq5ARR2IaZI0fvwFK5W1davsHmr8GOJe_uT0aEH3-6Rof1qo_K9lhRbxYwYbP2LtFEoNtRxxX26ISXXNEi_q7M_YM/file# [following]
--2020-12-08 14:47:05--  https://uc37cc22b4846ed01cb853dd2a34.dl.dropboxusercontent.com/cd/0/inline/BEqPOTOtNPaXYM0P7tSMoCaKJLNsSZvc6LzrbmecjeTq5ARR2IaZI0fvwFK5W

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("/content/google_stock_price_train.csv?dl=0")

In [4]:
df.head()

Date    Open    High     Low   Close      Volume
0  1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2  1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3  1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4  1/9/2012  322.04  322.29  309.46  620.76  11,688,800

In [5]:
df.tail()

Date    Open    High     Low   Close     Volume
1253  12/23/2016  790.90  792.74  787.28  789.91    623,400
1254  12/27/2016  790.68  797.86  787.66  791.55    789,100
1255  12/28/2016  793.70  794.23  783.20  785.05  1,153,800
1256  12/29/2016  783.33  785.93  778.92  782.79    744,300
1257  12/30/2016  782.75  782.78  770.41  771.82  1,770,000

In [6]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [7]:
df.describe()

Open         High          Low
count  1258.000000  1258.000000  1258.000000
mean    533.709833   537.880223   529.007409
std     151.904442   153.008811   150.552807
min     279.120000   281.210000   277.220000
25%     404.115000   406.765000   401.765000
50%     537.470000   540.750000   532.990000
75%     654.922500   662.587500   644.800000
max     816.680000   816.680000   805.140000

In [8]:
df.drop(['Date'],axis=1,inplace=True)

In [9]:
# converting string to float
l1 = []
for i in df['Close']:
  if ',' in i:
    s= i.split(',')
    x= ''.join(s)
    l1.append(float(x))
  else:
    l1.append(float(i))


In [10]:
l1[500]

1106.42

In [11]:
 df.drop(['Close'],axis=1,inplace=True)


In [12]:
 df['Close'] = l1

In [13]:
l2 = []
for i in df['Volume']:
  if ',' in i:
    s= i.split(',')
    x= ''.join(s)
    l2.append(int(x))
  else:
    l2.append(int(i))

In [14]:
 df.drop(['Volume'],axis=1,inplace=True)
 

In [15]:
df['Volume'] = l2

In [16]:
# Y ----> Close
# X----> Open	High	Low	 Volume
df.shape

(1258, 5)

In [17]:
X_train = df.iloc[:,:4].values
Y_train = df.iloc[:,4].values
X_test = df.values
X_train.shape , Y_train.shape

((1258, 4), (1258,))

In [18]:
X_train

array([[325.25, 332.83, 324.97, 663.59],
       [331.27, 333.87, 329.08, 666.45],
       [329.83, 330.75, 326.89, 657.21],
       ...,
       [793.7 , 794.23, 783.2 , 785.05],
       [783.33, 785.93, 778.92, 782.79],
       [782.75, 782.78, 770.41, 771.82]])

# Scaling

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
scale_X = StandardScaler()


In [21]:
X_train = scale_X.fit_transform(X_train)
X_test = scale_X.fit_transform(X_test)

In [22]:
print(X_train[:10,:])

[[-1.37285476 -1.34065332 -1.35579373 -0.29801768]
 [-1.33320882 -1.33385362 -1.32848349 -0.28065141]
 [-1.34269224 -1.35425271 -1.34303566 -0.33675781]
 [-1.35250493 -1.36719829 -1.36436556 -0.39122474]
 [-1.39399487 -1.40956563 -1.45885504 -0.55808663]
 [-1.44891964 -1.45252141 -1.47320787 -0.55401831]
 [-1.46940118 -1.46690539 -1.45925373 -0.53689493]
 [-1.44411208 -1.45552897 -1.44144558 -0.51461024]
 [-1.46037877 -1.47488196 -1.45945307 -0.54278488]
 [-1.44160951 -1.45847115 -1.44416996 -0.52104669]]


# Regression

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [24]:
X_train , X_test,Y_train , Y_test = train_test_split(X_train,Y_train,test_size=0.33)

In [25]:
lr = LinearRegression(normalize=True)

In [26]:
lr.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [27]:
print(lr.coef_) #slopes

[ -1809922.03988781  32045450.98386703 -31541712.43211652
    733548.38812239]


In [28]:
print(lr.score(X_train,Y_train))
print(lr.score(X_test,Y_test))

0.5047832174389035
0.5049302175264017
